name: Run tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    branches:
      - main
    paths:
      - '**.py'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
          python-version: ['3.8', '3.9', '3.10']
          wagtail-version: ['2.13', '2.14', '2.15', '2.16']
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install "wagtail~=${{ matrix.wagtail-version }}"
      - name: Test
        run: python -m pytest
